[2022-06-12 11:59:23,629] {processor.py:163} INFO - Started process (PID=360) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 11:59:23,640] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 11:59:23,710] {logging_mixin.py:109} INFO - [2022-06-12 11:59:23,710] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 11:59:53,908] {logging_mixin.py:109} INFO - [2022-06-12 11:59:53,907] {timeout.py:36} ERROR - Process timed out, PID: 360
[2022-06-12 11:59:54,106] {logging_mixin.py:109} INFO - [2022-06-12 11:59:53,941] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 108, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 360
[2022-06-12 11:59:54,819] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 11:59:55,182] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 31.758 seconds
[2022-06-12 12:00:56,512] {processor.py:163} INFO - Started process (PID=408) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:00:56,544] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:00:56,546] {logging_mixin.py:109} INFO - [2022-06-12 12:00:56,546] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:01:13,747] {logging_mixin.py:109} INFO - [2022-06-12 12:01:13,742] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:01:14,024] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:01:14,246] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 17.826 seconds
[2022-06-12 12:02:15,624] {processor.py:163} INFO - Started process (PID=449) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:02:15,736] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:02:15,798] {logging_mixin.py:109} INFO - [2022-06-12 12:02:15,797] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:02:29,567] {logging_mixin.py:109} INFO - [2022-06-12 12:02:29,331] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:02:31,125] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:02:31,782] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 16.464 seconds
[2022-06-12 12:03:34,763] {processor.py:163} INFO - Started process (PID=487) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:03:34,968] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:03:35,018] {logging_mixin.py:109} INFO - [2022-06-12 12:03:35,018] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:03:55,623] {logging_mixin.py:109} INFO - [2022-06-12 12:03:55,581] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:03:55,969] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:03:56,127] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 22.121 seconds
[2022-06-12 12:04:58,719] {processor.py:163} INFO - Started process (PID=525) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:04:58,960] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:04:59,098] {logging_mixin.py:109} INFO - [2022-06-12 12:04:59,097] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:05:29,331] {logging_mixin.py:109} INFO - [2022-06-12 12:05:29,225] {timeout.py:36} ERROR - Process timed out, PID: 525
[2022-06-12 12:05:29,431] {logging_mixin.py:109} INFO - [2022-06-12 12:05:29,428] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 34, in <module>
    from pandas.io.sql import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 525
[2022-06-12 12:05:30,499] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:05:31,151] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 32.881 seconds
[2022-06-12 12:06:33,855] {processor.py:163} INFO - Started process (PID=572) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:06:34,184] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:06:34,194] {logging_mixin.py:109} INFO - [2022-06-12 12:06:34,194] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:07:04,681] {logging_mixin.py:109} INFO - [2022-06-12 12:07:04,631] {timeout.py:36} ERROR - Process timed out, PID: 572
[2022-06-12 12:07:04,692] {logging_mixin.py:109} INFO - [2022-06-12 12:07:04,682] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 16, in <module>
    from pandas.io.json import read_json
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/__init__.py", line 1, in <module>
    from pandas.io.json._json import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 138, in <module>
    class Writer(ABC):
  File "/usr/local/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 572
[2022-06-12 12:07:04,853] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:07:05,111] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 31.800 seconds
[2022-06-12 12:08:06,574] {processor.py:163} INFO - Started process (PID=611) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:08:06,655] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:08:06,678] {logging_mixin.py:109} INFO - [2022-06-12 12:08:06,678] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:08:36,915] {logging_mixin.py:109} INFO - [2022-06-12 12:08:36,737] {timeout.py:36} ERROR - Process timed out, PID: 611
[2022-06-12 12:08:37,584] {logging_mixin.py:109} INFO - [2022-06-12 12:08:37,166] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 179, in <module>
    import pandas.testing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/testing.py", line 6, in <module>
    from pandas._testing import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_testing/__init__.py", line 58, in <module>
    from pandas._testing._io import (  # noqa:F401
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_testing/_io.py", line 23, in <module>
    from pandas._testing.contexts import ensure_clean
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_testing/contexts.py", line 6, in <module>
    import random
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 611
[2022-06-12 12:08:38,101] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:08:38,129] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 31.725 seconds
[2022-06-12 12:09:39,907] {processor.py:163} INFO - Started process (PID=660) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:09:39,990] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:09:40,093] {logging_mixin.py:109} INFO - [2022-06-12 12:09:40,093] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:10:10,413] {logging_mixin.py:109} INFO - [2022-06-12 12:10:10,373] {timeout.py:36} ERROR - Process timed out, PID: 660
[2022-06-12 12:10:10,689] {logging_mixin.py:109} INFO - [2022-06-12 12:10:10,414] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 122, in <module>
    from pandas.core.computation.api import eval
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/computation/eval.py", line 12, in <module>
    from pandas.core.computation.engines import ENGINES
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/computation/engines.py", line 12, in <module>
    from pandas.core.computation.expr import Expr
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 23, in <module>
    from pandas.core.computation.ops import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/computation/ops.py", line 29, in <module>
    from pandas.core.computation.scope import DEFAULT_GLOBALS
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/computation/scope.py", line 17, in <module>
    from pandas.compat.chainmap import DeepChainMap
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/chainmap.py", line 12, in <module>
    class DeepChainMap(ChainMap[_KT, _VT]):
  File "/usr/local/lib/python3.7/abc.py", line 127, in __new__
    _abc_init(cls)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 660
[2022-06-12 12:10:11,621] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:10:12,549] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 32.804 seconds
[2022-06-12 12:11:19,657] {processor.py:163} INFO - Started process (PID=724) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:11:20,420] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:11:20,702] {logging_mixin.py:109} INFO - [2022-06-12 12:11:20,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:11:51,635] {logging_mixin.py:109} INFO - [2022-06-12 12:11:50,947] {timeout.py:36} ERROR - Process timed out, PID: 724
[2022-06-12 12:11:52,516] {logging_mixin.py:109} INFO - [2022-06-12 12:11:51,700] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 124, in <module>
    from pandas.core.reshape.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/api.py", line 9, in <module>
    from pandas.core.reshape.merge import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 602, in <module>
    class _MergeOperation:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1040, in _MergeOperation
    def _get_merge_keys(self):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 724
[2022-06-12 12:11:53,869] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:11:54,750] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 37.369 seconds
[2022-06-12 12:12:57,385] {processor.py:163} INFO - Started process (PID=773) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:12:57,425] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:12:57,467] {logging_mixin.py:109} INFO - [2022-06-12 12:12:57,457] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:13:27,664] {logging_mixin.py:109} INFO - [2022-06-12 12:13:27,560] {timeout.py:36} ERROR - Process timed out, PID: 773
[2022-06-12 12:13:30,323] {logging_mixin.py:109} INFO - [2022-06-12 12:13:27,799] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 144, in <module>
    from pandas.core.window import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (  # noqa:F401
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/window/ewm.py", line 43, in <module>
    from pandas.core.window.numba_ import generate_numba_ewma_func
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 773
[2022-06-12 12:13:31,859] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:13:31,957] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 35.063 seconds
[2022-06-12 12:14:36,754] {processor.py:163} INFO - Started process (PID=817) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:14:37,338] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:14:37,482] {logging_mixin.py:109} INFO - [2022-06-12 12:14:37,482] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:15:07,752] {logging_mixin.py:109} INFO - [2022-06-12 12:15:07,501] {timeout.py:36} ERROR - Process timed out, PID: 817
[2022-06-12 12:15:07,777] {logging_mixin.py:109} INFO - [2022-06-12 12:15:07,753] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/compat.pxi", line 49, in init pyarrow.lib
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/__init__.py", line 7, in <module>
    from cloudpickle.cloudpickle import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 817
[2022-06-12 12:15:09,991] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:15:12,635] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 36.970 seconds
[2022-06-12 12:16:18,132] {processor.py:163} INFO - Started process (PID=865) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:16:18,410] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:16:18,540] {logging_mixin.py:109} INFO - [2022-06-12 12:16:18,486] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:16:49,505] {logging_mixin.py:109} INFO - [2022-06-12 12:16:48,886] {timeout.py:36} ERROR - Process timed out, PID: 865
[2022-06-12 12:16:50,582] {logging_mixin.py:109} INFO - [2022-06-12 12:16:49,613] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/nattype.pyx", line 1, in init pandas._libs.tslibs.nattype
  File "<frozen importlib._bootstrap>", line 978, in _find_and_load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 865
[2022-06-12 12:16:55,255] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:16:57,693] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 39.734 seconds
[2022-06-12 12:18:02,501] {processor.py:163} INFO - Started process (PID=909) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:18:03,182] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:18:03,524] {logging_mixin.py:109} INFO - [2022-06-12 12:18:03,184] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:18:35,386] {logging_mixin.py:109} INFO - [2022-06-12 12:18:34,552] {timeout.py:36} ERROR - Process timed out, PID: 909
[2022-06-12 12:18:37,033] {logging_mixin.py:109} INFO - [2022-06-12 12:18:35,613] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/__init__.py", line 156, in <module>
    from . import random
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/random/__init__.py", line 179, in <module>
    from . import _pickle
  File "/home/airflow/.local/lib/python3.7/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 19, in init numpy.random.mtrand
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 909
[2022-06-12 12:18:41,877] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:18:43,487] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 42.316 seconds
[2022-06-12 12:19:50,245] {processor.py:163} INFO - Started process (PID=920) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:19:50,739] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:19:51,728] {logging_mixin.py:109} INFO - [2022-06-12 12:19:51,728] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:20:23,574] {logging_mixin.py:109} INFO - [2022-06-12 12:20:23,333] {timeout.py:36} ERROR - Process timed out, PID: 920
[2022-06-12 12:20:23,809] {logging_mixin.py:109} INFO - [2022-06-12 12:20:23,585] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 7, in <module>
    from pandas.core.util.hashing import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 17, in <module>
    from pandas._libs import lib
  File "pandas/_libs/lib.pyx", line 86, in init pandas._libs.lib
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 920
[2022-06-12 12:20:26,473] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:20:28,310] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 41.000 seconds
[2022-06-12 12:21:31,217] {processor.py:163} INFO - Started process (PID=926) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:21:31,342] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:21:31,401] {logging_mixin.py:109} INFO - [2022-06-12 12:21:31,401] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:22:01,791] {logging_mixin.py:109} INFO - [2022-06-12 12:22:01,633] {timeout.py:36} ERROR - Process timed out, PID: 926
[2022-06-12 12:22:02,182] {logging_mixin.py:109} INFO - [2022-06-12 12:22:01,894] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 8, in <module>
    from pandas.io.excel import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/__init__.py", line 1, in <module>
    from pandas.io.excel._base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 61, in <module>
    from pandas.io.parsers import TextParser
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 45, in <module>
    from pandas.io.parsers.base_parser import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 70, in <module>
    from pandas.io.date_converters import generic_parser
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 926
[2022-06-12 12:22:02,865] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:22:03,725] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 33.149 seconds
[2022-06-12 12:23:05,073] {processor.py:163} INFO - Started process (PID=938) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:23:05,081] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:23:05,085] {logging_mixin.py:109} INFO - [2022-06-12 12:23:05,084] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:23:14,051] {logging_mixin.py:109} INFO - [2022-06-12 12:23:13,850] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:23:14,463] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:23:15,010] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 10.005 seconds
[2022-06-12 12:24:15,943] {processor.py:163} INFO - Started process (PID=976) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:24:15,977] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:24:15,991] {logging_mixin.py:109} INFO - [2022-06-12 12:24:15,991] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:24:26,407] {logging_mixin.py:109} INFO - [2022-06-12 12:24:26,277] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:24:26,991] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:24:27,226] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 11.352 seconds
[2022-06-12 12:25:28,231] {processor.py:163} INFO - Started process (PID=1008) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:25:28,406] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:25:28,431] {logging_mixin.py:109} INFO - [2022-06-12 12:25:28,430] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:25:41,651] {logging_mixin.py:109} INFO - [2022-06-12 12:25:41,603] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:25:41,950] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:25:42,176] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 14.386 seconds
[2022-06-12 12:26:43,447] {processor.py:163} INFO - Started process (PID=1048) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:26:43,455] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:26:43,512] {logging_mixin.py:109} INFO - [2022-06-12 12:26:43,457] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:26:50,610] {logging_mixin.py:109} INFO - [2022-06-12 12:26:50,535] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:26:50,902] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:26:51,265] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 8.060 seconds
[2022-06-12 12:27:54,090] {processor.py:163} INFO - Started process (PID=1078) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:27:54,381] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:27:54,392] {logging_mixin.py:109} INFO - [2022-06-12 12:27:54,389] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:28:23,460] {logging_mixin.py:109} INFO - [2022-06-12 12:28:23,233] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:28:27,680] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:28:29,592] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 36.362 seconds
[2022-06-12 12:29:31,735] {processor.py:163} INFO - Started process (PID=1125) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:29:32,041] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:29:32,091] {logging_mixin.py:109} INFO - [2022-06-12 12:29:32,043] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:30:01,903] {logging_mixin.py:109} INFO - [2022-06-12 12:30:01,604] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:30:03,557] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:30:04,539] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 33.249 seconds
[2022-06-12 12:31:07,895] {processor.py:163} INFO - Started process (PID=1169) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:31:08,201] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:31:08,231] {logging_mixin.py:109} INFO - [2022-06-12 12:31:08,230] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:31:33,925] {logging_mixin.py:109} INFO - [2022-06-12 12:31:33,796] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 18, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 12:31:35,341] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:31:35,914] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 28.744 seconds
[2022-06-12 12:32:38,540] {processor.py:163} INFO - Started process (PID=1207) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:32:39,145] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:32:39,147] {logging_mixin.py:109} INFO - [2022-06-12 12:32:39,147] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:33:09,586] {logging_mixin.py:109} INFO - [2022-06-12 12:33:09,307] {timeout.py:36} ERROR - Process timed out, PID: 1207
[2022-06-12 12:33:10,030] {logging_mixin.py:109} INFO - [2022-06-12 12:33:09,603] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/version/__init__.py", line 332, in <module>
    class Version(_BaseVersion):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/version/__init__.py", line 415, in Version
    @property
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 1207
[2022-06-12 12:33:12,358] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:33:15,843] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 38.212 seconds
[2022-06-12 12:34:19,675] {processor.py:163} INFO - Started process (PID=1254) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:34:19,927] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:34:20,088] {logging_mixin.py:109} INFO - [2022-06-12 12:34:20,087] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:34:50,757] {logging_mixin.py:109} INFO - [2022-06-12 12:34:50,443] {timeout.py:36} ERROR - Process timed out, PID: 1254
[2022-06-12 12:34:52,233] {logging_mixin.py:109} INFO - [2022-06-12 12:34:50,777] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 113, in <module>
    from pandas.core.strings.object_array import ObjectStringArrayMixin
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/__init__.py", line 30, in <module>
    from pandas.core.strings.accessor import StringMethods
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 134, in <module>
    class StringMethods(NoNewAttributesMixin):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 1540, in StringMethods
    def center(self, width, fillchar=" "):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 487, in __call__
    func.__doc__ = dedent(self.join.join(docitems))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 1254
[2022-06-12 12:34:55,246] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:34:56,616] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 38.429 seconds
[2022-06-12 12:35:59,239] {processor.py:163} INFO - Started process (PID=1301) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:35:59,687] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:35:59,800] {logging_mixin.py:109} INFO - [2022-06-12 12:35:59,799] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:36:30,415] {logging_mixin.py:109} INFO - [2022-06-12 12:36:30,244] {timeout.py:36} ERROR - Process timed out, PID: 1301
[2022-06-12 12:36:30,572] {logging_mixin.py:109} INFO - [2022-06-12 12:36:30,480] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 8, in <module>
    from pandas.core.arrays.datetimes import DatetimeArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 77, in <module>
    from pandas.tseries.offsets import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 1301
[2022-06-12 12:36:32,614] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:36:33,477] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 35.292 seconds
[2022-06-12 12:37:36,359] {processor.py:163} INFO - Started process (PID=1348) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:37:36,566] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:37:36,738] {logging_mixin.py:109} INFO - [2022-06-12 12:37:36,737] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:38:08,697] {logging_mixin.py:109} INFO - [2022-06-12 12:38:07,730] {timeout.py:36} ERROR - Process timed out, PID: 1348
[2022-06-12 12:38:10,167] {logging_mixin.py:109} INFO - [2022-06-12 12:38:08,699] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 29, in <module>
    from pandas._libs import (
  File "pandas/_libs/reduction.pyx", line 23, in init pandas._libs.reduction
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 1348
[2022-06-12 12:38:11,490] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:38:12,909] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 37.294 seconds
[2022-06-12 12:39:19,605] {processor.py:163} INFO - Started process (PID=1394) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:39:20,050] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:39:20,250] {logging_mixin.py:109} INFO - [2022-06-12 12:39:20,250] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:39:51,287] {logging_mixin.py:109} INFO - [2022-06-12 12:39:50,850] {timeout.py:36} ERROR - Process timed out, PID: 1394
[2022-06-12 12:39:51,858] {logging_mixin.py:109} INFO - [2022-06-12 12:39:51,591] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "<frozen importlib._bootstrap>", line 978, in _find_and_load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 1394
[2022-06-12 12:39:53,978] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:39:56,181] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 38.296 seconds
[2022-06-12 12:41:03,447] {processor.py:163} INFO - Started process (PID=1443) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:41:03,639] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:41:04,199] {logging_mixin.py:109} INFO - [2022-06-12 12:41:04,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:41:35,234] {logging_mixin.py:109} INFO - [2022-06-12 12:41:34,820] {timeout.py:36} ERROR - Process timed out, PID: 1443
[2022-06-12 12:41:36,126] {logging_mixin.py:109} INFO - [2022-06-12 12:41:35,469] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 205, in <module>
    from pyarrow.ipc import serialize_pandas, deserialize_pandas
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 1443
[2022-06-12 12:41:40,037] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:41:41,491] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 40.220 seconds
[2022-06-12 12:42:47,056] {processor.py:163} INFO - Started process (PID=1491) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:42:47,419] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 12:42:47,543] {logging_mixin.py:109} INFO - [2022-06-12 12:42:47,542] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:43:18,452] {logging_mixin.py:109} INFO - [2022-06-12 12:43:17,833] {timeout.py:36} ERROR - Process timed out, PID: 1491
[2022-06-12 12:43:19,099] {logging_mixin.py:109} INFO - [2022-06-12 12:43:18,452] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.base import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 60, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 28, in <module>
    from pandas.core import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/etl_first_run.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 1491
[2022-06-12 12:43:21,256] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 12:43:22,250] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 36.168 seconds
[2022-06-12 13:07:41,920] {processor.py:163} INFO - Started process (PID=304) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:07:42,379] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:07:42,560] {logging_mixin.py:109} INFO - [2022-06-12 13:07:42,544] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:07:45,328] {logging_mixin.py:109} INFO - [2022-06-12 13:07:44,775] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/etl_first_run.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_first_run.py", line 11, in <module>
    from variables import *
ModuleNotFoundError: No module named 'variables'
[2022-06-12 13:07:46,506] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:07:46,844] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 5.708 seconds
[2022-06-12 13:08:48,908] {processor.py:163} INFO - Started process (PID=332) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:08:49,047] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:08:49,066] {logging_mixin.py:109} INFO - [2022-06-12 13:08:49,065] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:09:02,234] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:09:43,707] {processor.py:163} INFO - Started process (PID=362) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:09:43,782] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:09:43,821] {logging_mixin.py:109} INFO - [2022-06-12 13:09:43,820] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:09:44,927] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:39:18,319] {processor.py:163} INFO - Started process (PID=253) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:39:18,361] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:39:18,381] {logging_mixin.py:109} INFO - [2022-06-12 13:39:18,380] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:39:22,324] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:40:17,830] {processor.py:163} INFO - Started process (PID=282) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:40:17,907] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:40:17,954] {logging_mixin.py:109} INFO - [2022-06-12 13:40:17,954] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:40:19,528] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:41:17,718] {processor.py:163} INFO - Started process (PID=312) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:41:17,814] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:41:17,852] {logging_mixin.py:109} INFO - [2022-06-12 13:41:17,842] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:41:19,402] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:42:15,551] {processor.py:163} INFO - Started process (PID=334) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:42:15,859] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:42:16,008] {logging_mixin.py:109} INFO - [2022-06-12 13:42:15,994] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:42:18,018] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:43:15,303] {processor.py:163} INFO - Started process (PID=371) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:43:15,317] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:43:15,319] {logging_mixin.py:109} INFO - [2022-06-12 13:43:15,319] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:43:17,417] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:44:13,281] {processor.py:163} INFO - Started process (PID=395) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:44:13,361] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:44:13,430] {logging_mixin.py:109} INFO - [2022-06-12 13:44:13,429] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:44:15,684] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:45:05,679] {processor.py:163} INFO - Started process (PID=423) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:45:05,917] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:45:05,928] {logging_mixin.py:109} INFO - [2022-06-12 13:45:05,927] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:45:08,089] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:45:59,758] {processor.py:163} INFO - Started process (PID=454) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:45:59,794] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:45:59,920] {logging_mixin.py:109} INFO - [2022-06-12 13:45:59,919] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:46:01,437] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:46:55,255] {processor.py:163} INFO - Started process (PID=478) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:46:55,420] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:46:55,538] {logging_mixin.py:109} INFO - [2022-06-12 13:46:55,538] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:46:57,289] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:47:48,563] {processor.py:163} INFO - Started process (PID=508) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:47:48,770] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:47:48,851] {logging_mixin.py:109} INFO - [2022-06-12 13:47:48,851] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:47:50,211] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:48:40,383] {processor.py:163} INFO - Started process (PID=537) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:48:40,438] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:48:40,453] {logging_mixin.py:109} INFO - [2022-06-12 13:48:40,452] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:48:41,014] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:49:34,277] {processor.py:163} INFO - Started process (PID=561) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:49:34,359] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:49:34,392] {logging_mixin.py:109} INFO - [2022-06-12 13:49:34,391] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:49:35,814] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:50:11,319] {logging_mixin.py:109} INFO - [2022-06-12 13:50:11,319] {manager.py:496} INFO - Created Permission View: can edit on DAG:etl_dag
[2022-06-12 13:50:11,415] {logging_mixin.py:109} INFO - [2022-06-12 13:50:11,415] {manager.py:496} INFO - Created Permission View: can read on DAG:etl_dag
[2022-06-12 13:50:11,418] {logging_mixin.py:109} INFO - [2022-06-12 13:50:11,417] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:50:11,484] {logging_mixin.py:109} INFO - [2022-06-12 13:50:11,483] {dag.py:2415} INFO - Creating ORM DAG for etl_dag
[2022-06-12 13:50:11,555] {logging_mixin.py:109} INFO - [2022-06-12 13:50:11,555] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:50:11,626] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 37.452 seconds
[2022-06-12 13:51:13,139] {processor.py:163} INFO - Started process (PID=612) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:51:13,144] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:51:13,249] {logging_mixin.py:109} INFO - [2022-06-12 13:51:13,248] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:51:14,116] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:51:14,224] {logging_mixin.py:109} INFO - [2022-06-12 13:51:14,223] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:51:14,330] {logging_mixin.py:109} INFO - [2022-06-12 13:51:14,329] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:51:14,423] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 1.518 seconds
[2022-06-12 13:52:15,286] {processor.py:163} INFO - Started process (PID=647) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:52:15,337] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:52:15,359] {logging_mixin.py:109} INFO - [2022-06-12 13:52:15,359] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:52:16,203] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:52:16,340] {logging_mixin.py:109} INFO - [2022-06-12 13:52:16,339] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:52:16,540] {logging_mixin.py:109} INFO - [2022-06-12 13:52:16,539] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:52:16,622] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 1.472 seconds
[2022-06-12 13:53:17,481] {processor.py:163} INFO - Started process (PID=678) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:53:17,489] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:53:17,493] {logging_mixin.py:109} INFO - [2022-06-12 13:53:17,492] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:53:17,618] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:53:17,648] {logging_mixin.py:109} INFO - [2022-06-12 13:53:17,647] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:53:17,735] {logging_mixin.py:109} INFO - [2022-06-12 13:53:17,734] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:53:17,755] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.346 seconds
[2022-06-12 13:54:18,649] {processor.py:163} INFO - Started process (PID=706) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:54:18,676] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:54:18,707] {logging_mixin.py:109} INFO - [2022-06-12 13:54:18,707] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:54:19,393] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:54:19,443] {logging_mixin.py:109} INFO - [2022-06-12 13:54:19,443] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:54:19,525] {logging_mixin.py:109} INFO - [2022-06-12 13:54:19,525] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:54:19,545] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.941 seconds
[2022-06-12 13:55:20,129] {processor.py:163} INFO - Started process (PID=733) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:55:20,163] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:55:20,197] {logging_mixin.py:109} INFO - [2022-06-12 13:55:20,197] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:55:20,785] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:55:20,947] {logging_mixin.py:109} INFO - [2022-06-12 13:55:20,947] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:55:21,130] {logging_mixin.py:109} INFO - [2022-06-12 13:55:21,130] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:55:21,219] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 1.248 seconds
[2022-06-12 13:56:21,504] {processor.py:163} INFO - Started process (PID=761) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:56:21,514] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:56:21,524] {logging_mixin.py:109} INFO - [2022-06-12 13:56:21,524] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:56:21,753] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:56:21,811] {logging_mixin.py:109} INFO - [2022-06-12 13:56:21,811] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:56:21,847] {logging_mixin.py:109} INFO - [2022-06-12 13:56:21,847] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:56:21,869] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.430 seconds
[2022-06-12 13:57:22,667] {processor.py:163} INFO - Started process (PID=789) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:57:22,677] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:57:22,704] {logging_mixin.py:109} INFO - [2022-06-12 13:57:22,703] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:57:23,126] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:57:23,215] {logging_mixin.py:109} INFO - [2022-06-12 13:57:23,215] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:57:23,313] {logging_mixin.py:109} INFO - [2022-06-12 13:57:23,313] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:57:23,553] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.934 seconds
[2022-06-12 13:58:24,041] {processor.py:163} INFO - Started process (PID=817) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:58:24,069] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:58:24,073] {logging_mixin.py:109} INFO - [2022-06-12 13:58:24,072] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:58:25,027] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:58:25,214] {logging_mixin.py:109} INFO - [2022-06-12 13:58:25,213] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:58:25,298] {logging_mixin.py:109} INFO - [2022-06-12 13:58:25,298] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:58:25,348] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 1.387 seconds
[2022-06-12 13:59:26,580] {processor.py:163} INFO - Started process (PID=847) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:59:26,592] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 13:59:26,596] {logging_mixin.py:109} INFO - [2022-06-12 13:59:26,596] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:59:26,869] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 13:59:27,029] {logging_mixin.py:109} INFO - [2022-06-12 13:59:27,028] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 13:59:27,106] {logging_mixin.py:109} INFO - [2022-06-12 13:59:27,106] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 13:59:27,171] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.648 seconds
[2022-06-12 14:00:27,330] {processor.py:163} INFO - Started process (PID=876) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:00:27,349] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:00:27,358] {logging_mixin.py:109} INFO - [2022-06-12 14:00:27,358] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:00:27,711] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:00:27,796] {logging_mixin.py:109} INFO - [2022-06-12 14:00:27,796] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:00:27,897] {logging_mixin.py:109} INFO - [2022-06-12 14:00:27,897] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:00:27,923] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.637 seconds
[2022-06-12 14:01:28,228] {processor.py:163} INFO - Started process (PID=904) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:01:28,244] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:01:28,247] {logging_mixin.py:109} INFO - [2022-06-12 14:01:28,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:01:28,499] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:01:28,598] {logging_mixin.py:109} INFO - [2022-06-12 14:01:28,598] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:01:28,823] {logging_mixin.py:109} INFO - [2022-06-12 14:01:28,823] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:01:28,963] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.809 seconds
[2022-06-12 14:02:29,953] {processor.py:163} INFO - Started process (PID=933) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:02:29,961] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:02:29,964] {logging_mixin.py:109} INFO - [2022-06-12 14:02:29,964] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:02:30,082] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:02:30,151] {logging_mixin.py:109} INFO - [2022-06-12 14:02:30,150] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:02:30,194] {logging_mixin.py:109} INFO - [2022-06-12 14:02:30,193] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:02:30,218] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.316 seconds
[2022-06-12 14:03:30,814] {processor.py:163} INFO - Started process (PID=962) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:03:30,820] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:03:30,822] {logging_mixin.py:109} INFO - [2022-06-12 14:03:30,822] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:03:30,971] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:03:30,994] {logging_mixin.py:109} INFO - [2022-06-12 14:03:30,994] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:03:31,070] {logging_mixin.py:109} INFO - [2022-06-12 14:03:31,070] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:03:31,095] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.297 seconds
[2022-06-12 14:04:31,702] {processor.py:163} INFO - Started process (PID=991) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:04:31,707] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:04:31,710] {logging_mixin.py:109} INFO - [2022-06-12 14:04:31,709] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:04:31,826] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:04:31,861] {logging_mixin.py:109} INFO - [2022-06-12 14:04:31,861] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:04:31,894] {logging_mixin.py:109} INFO - [2022-06-12 14:04:31,894] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:04:31,937] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.253 seconds
[2022-06-12 14:05:32,591] {processor.py:163} INFO - Started process (PID=1019) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:05:32,597] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:05:32,600] {logging_mixin.py:109} INFO - [2022-06-12 14:05:32,600] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:05:32,781] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:05:32,808] {logging_mixin.py:109} INFO - [2022-06-12 14:05:32,808] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:05:32,916] {logging_mixin.py:109} INFO - [2022-06-12 14:05:32,915] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:05:32,932] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.402 seconds
[2022-06-12 14:06:34,062] {processor.py:163} INFO - Started process (PID=1046) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:06:34,101] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:06:34,128] {logging_mixin.py:109} INFO - [2022-06-12 14:06:34,111] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:06:34,837] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:06:35,117] {logging_mixin.py:109} INFO - [2022-06-12 14:06:35,117] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:06:35,235] {logging_mixin.py:109} INFO - [2022-06-12 14:06:35,235] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:06:35,317] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 1.337 seconds
[2022-06-12 14:07:36,698] {processor.py:163} INFO - Started process (PID=1083) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:07:36,741] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:07:36,747] {logging_mixin.py:109} INFO - [2022-06-12 14:07:36,746] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:07:37,241] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:07:37,299] {logging_mixin.py:109} INFO - [2022-06-12 14:07:37,299] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:07:37,377] {logging_mixin.py:109} INFO - [2022-06-12 14:07:37,377] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:07:37,459] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.873 seconds
[2022-06-12 14:08:38,418] {processor.py:163} INFO - Started process (PID=1111) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:08:38,439] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:08:38,448] {logging_mixin.py:109} INFO - [2022-06-12 14:08:38,444] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:08:38,639] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:08:38,667] {logging_mixin.py:109} INFO - [2022-06-12 14:08:38,667] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:08:38,710] {logging_mixin.py:109} INFO - [2022-06-12 14:08:38,709] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:08:38,741] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.369 seconds
[2022-06-12 14:09:39,607] {processor.py:163} INFO - Started process (PID=1139) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:09:39,631] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:09:39,648] {logging_mixin.py:109} INFO - [2022-06-12 14:09:39,648] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:09:40,043] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:09:40,099] {logging_mixin.py:109} INFO - [2022-06-12 14:09:40,098] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:09:40,295] {logging_mixin.py:109} INFO - [2022-06-12 14:09:40,295] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:09:40,378] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.823 seconds
[2022-06-12 14:10:41,332] {processor.py:163} INFO - Started process (PID=1168) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:10:41,367] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:10:41,374] {logging_mixin.py:109} INFO - [2022-06-12 14:10:41,374] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:10:41,751] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:10:42,075] {logging_mixin.py:109} INFO - [2022-06-12 14:10:42,072] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:10:42,317] {logging_mixin.py:109} INFO - [2022-06-12 14:10:42,317] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:10:42,420] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 1.127 seconds
[2022-06-12 14:11:43,655] {processor.py:163} INFO - Started process (PID=1196) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:11:43,661] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:11:43,665] {logging_mixin.py:109} INFO - [2022-06-12 14:11:43,664] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:11:44,107] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:11:44,367] {logging_mixin.py:109} INFO - [2022-06-12 14:11:44,366] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:11:44,571] {logging_mixin.py:109} INFO - [2022-06-12 14:11:44,571] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:11:44,745] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 1.114 seconds
[2022-06-12 14:12:45,499] {processor.py:163} INFO - Started process (PID=1224) to work on /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:12:45,519] {processor.py:642} INFO - Processing file /opt/airflow/dags/etl_first_run.py for tasks to queue
[2022-06-12 14:12:45,522] {logging_mixin.py:109} INFO - [2022-06-12 14:12:45,522] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:12:45,749] {processor.py:654} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_first_run.py
[2022-06-12 14:12:45,809] {logging_mixin.py:109} INFO - [2022-06-12 14:12:45,807] {dag.py:2396} INFO - Sync 1 DAGs
[2022-06-12 14:12:45,881] {logging_mixin.py:109} INFO - [2022-06-12 14:12:45,881] {dag.py:2935} INFO - Setting next_dagrun for etl_dag to None
[2022-06-12 14:12:45,930] {processor.py:171} INFO - Processing /opt/airflow/dags/etl_first_run.py took 0.505 seconds
